# Generated by Django 5.2.5 on 2025-08-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwiftLogix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
