# Generated by Django 5.2.5 on 2025-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwiftLogix', '0002_shipment_current_latitude_shipment_current_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
