# Generated by Django 5.2.5 on 2025-08-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwiftLogix', '0003_alter_shipment_pickup_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote Request', 'verbose_name_plural': 'Quote Requests'},
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Location'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='departure',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departure Location'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Message'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimensions (LxWxH cm)'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='freight_type',
            field=models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight'), ('road', 'Road Transport'), ('rail', 'Rail Transport')], max_length=10, verbose_name='Freight Type'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quote Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='special_note',
            field=models.TextField(blank=True, verbose_name='Special Notes'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Weight (kg)'),
        ),
    ]
